export const MOCK_MOVIES = [
  { id: 'tt1375666', Title: 'Inception', Poster: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', Year: '2010', imdbID: 'tt1375666', Type: 'movie', Rated: 'PG-13', Plot: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Genre: 'Action, Adventure, Sci-Fi', Director: 'Christopher Nolan', Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', Runtime: '148 min' },
  { id: 'tt0137523', Title: 'Fight Club', Poster: 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg', Year: '1999', imdbID: 'tt0137523', Type: 'movie', Rated: 'R', Plot: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Genre: 'Drama', Director: 'David Fincher', Actors: 'Brad Pitt, Edward Norton, Helena Bonham Carter', Runtime: '139 min' },
  { id: 'tt0110912', Title: 'Pulp Fiction', Poster: 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg', Year: '1994', imdbID: 'tt0110912', Type: 'movie', Rated: 'R', Plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', Ratings: [{ Source: 'Internet Movie Database', Value: '8.9/10' }], Genre: 'Crime, Drama', Director: 'Quentin Tarantino', Actors: 'John Travolta, Uma Thurman, Samuel L. Jackson', Runtime: '154 min' },
  { id: 'tt0111161', Title: 'The Shawshank Redemption', Poster: 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg', Year: '1994', imdbID: 'tt0111161', Type: 'movie', Rated: 'R', Plot: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.', Ratings: [{ Source: 'Internet Movie Database', Value: '9.3/10' }], Genre: 'Drama', Director: 'Frank Darabont', Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton', Runtime: '142 min' },
  { id: 'tt0068646', Title: 'The Godfather', Poster: 'https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_SX300.jpg', Year: '1972', imdbID: 'tt0068646', Type: 'movie', Rated: 'R', Plot: 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael.', Ratings: [{ Source: 'Internet Movie Database', Value: '9.2/10' }], Genre: 'Crime, Drama', Director: 'Francis Ford Coppola', Actors: 'Marlon Brando, Al Pacino, James Caan', Runtime: '175 min' },
  { id: 'tt0468569', Title: 'The Dark Knight', Poster: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', Year: '2008', imdbID: 'tt0468569', Type: 'movie', Rated: 'PG-13', Plot: 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.', Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }], Genre: 'Action, Crime, Drama', Director: 'Christopher Nolan', Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart', Runtime: '152 min' },
  { id: 'tt0109830', Title: 'Forrest Gump', Poster: 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg', Year: '1994', imdbID: 'tt0109830', Type: 'movie', Rated: 'PG-13', Plot: 'The history of the United States from the 1950s to the 1970s through the eyes of an Alabama man with an IQ of 75.', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Genre: 'Drama, Romance', Director: 'Robert Zemeckis', Actors: 'Tom Hanks, Robin Wright, Gary Sinise', Runtime: '142 min' },
  { id: 'tt0133093', Title: 'The Matrix', Poster: 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZDY5NjM1MTg0XkEyXkFqcGc@._V1_SX300.jpg', Year: '1999', imdbID: 'tt0133093', Type: 'movie', Rated: 'R', Plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth.', Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }], Genre: 'Action, Sci-Fi', Director: 'Lana Wachowski, Lilly Wachowski', Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', Runtime: '136 min' },
  { id: 'tt1241982', Title: 'Blade (2025)', Poster: 'https://m.media-amazon.com/images/M/MV5BMTkzNjc1ODktMzllMi00NWM3LWE0NjItMjIxYjUxZWU4NjI4XkEyXkFqcGc@._V1_SX300.jpg', Year: '2025', imdbID: 'tt1241982', Type: 'movie', Rated: 'R', Plot: 'A reboot of the Marvel vampire hunter franchise starring Mahershala Ali as the half-human, half-vampire Blade.', Ratings: [{ Source: 'Internet Movie Database', Value: '0/10' }], Genre: 'Action, Horror, Sci-Fi', Director: 'Yann Demange', Actors: 'Mahershala Ali, Aaron Pierre, Mia Goth', Runtime: 'TBD' },
];

export const MOCK_UPCOMING = [
  { ...MOCK_MOVIES[8] },
  { id: 'tt9603212', Title: 'Mission: Impossible 8', Poster: 'https://m.media-amazon.com/images/M/MV5BZGQ1NWY3MGEtZmQxZi00YjcxLWIzY2MtNDY5ZWEzNjYyMjg3XkEyXkFqcGc@._V1_SX300.jpg', Year: '2025', imdbID: 'tt9603212', Type: 'movie', Plot: 'Ethan Hunt faces his most dangerous mission yet as a global threat emerges.', Genre: 'Action, Adventure', Director: 'Christopher McQuarrie', Actors: 'Tom Cruise, Hayley Atwell, Simon Pegg' },
  { id: 'tt6263850', Title: 'Deadpool & Wolverine', Poster: 'https://m.media-amazon.com/images/M/MV5BMDkzYjE1ZmMtZjkzNS00OTZiLWFmMmQtYjA5ZDliNjc1MjBhXkEyXkFqcGc@._V1_SX300.jpg', Year: '2024', imdbID: 'tt6263850', Type: 'movie', Plot: 'Deadpool is recruited by the TVA to save his world from extinction alongside Wolverine.', Genre: 'Action, Comedy, Sci-Fi', Director: 'Shawn Levy', Actors: 'Ryan Reynolds, Hugh Jackman, Emma Corrin' },
  { id: 'tt15239678', Title: 'Dune: Part Two', Poster: 'https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5MzA3XkEyXkFqcGc@._V1_SX300.jpg', Year: '2024', imdbID: 'tt15239678', Type: 'movie', Plot: 'Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family.', Genre: 'Action, Adventure, Drama', Director: 'Denis Villeneuve', Actors: 'Timothée Chalamet, Zendaya, Austin Butler' },
];
